"""empty message

Revision ID: 6596c99dae14
Revises: ccfe6763370f
Create Date: 2024-01-19 18:49:01.636692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6596c99dae14'
down_revision = 'ccfe6763370f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acesso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_empresa')

    # ### end Alembic commands ###
