"""Correção campo ddd na tabela telefone

Revision ID: c3b3c1b16079
Revises: f6a3f2372970
Create Date: 2024-01-18 20:50:22.179010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b3c1b16079'
down_revision = 'f6a3f2372970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ddd', sa.String(length=2), nullable=True))
        batch_op.drop_column('dd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dd', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.drop_column('ddd')

    # ### end Alembic commands ###
