"""Criado tabelas funcao e responsavel

Revision ID: c5b10e3bc965
Revises: 
Create Date: 2024-01-29 21:01:48.898170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b10e3bc965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uf', sa.CHAR(length=2), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('codigo_ibge', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logradouro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ddi', sa.String(length=4), nullable=False),
    sa.Column('ddd', sa.String(length=2), nullable=False),
    sa.Column('numero', sa.String(length=9), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_ibge', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papel_rotina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_papel', sa.Integer(), nullable=False),
    sa.Column('id_rotina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_papel'], ['papel.id'], ),
    sa.ForeignKeyConstraint(['id_rotina'], ['rotina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('id_logradouro', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=60), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=60), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['id_logradouro'], ['logradouro.id'], ),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_fantasia', sa.String(length=60), nullable=False),
    sa.Column('razao_social', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('usuario', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('data_atualizacao', sa.Date(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('empresa_telefone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_telefone', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_telefone'], ['telefone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_acao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_rotina', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('data_acao', sa.Date(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False, comment='1 = Sucesso, 2 = Falha, 3 = Não autorizado'),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_rotina'], ['rotina.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_acesso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('data_acesso', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_papel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_papel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_papel'], ['papel.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_telefone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_telefone', sa.Integer(), nullable=False),
    sa.Column('telefone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_telefone'], ['telefone.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_setor', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('plaqueta', sa.String(length=30), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=True),
    sa.Column('data_tombamento', sa.Date(), nullable=True),
    sa.Column('data_baixa', sa.Date(), nullable=True),
    sa.Column('valor_compra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_depreciado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_contabil', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_setor'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_setor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_setor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_setor'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_bem', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.Date(), nullable=False),
    sa.Column('id_setor_saida', sa.Integer(), nullable=True),
    sa.Column('id_setor_entrada', sa.Integer(), nullable=True),
    sa.Column('id_empresa_saida', sa.Integer(), nullable=True),
    sa.Column('id_empresa_entrada', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_bem'], ['bem.id'], ),
    sa.ForeignKeyConstraint(['id_empresa_entrada'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_empresa_saida'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_setor_entrada'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['id_setor_saida'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    op.drop_table('usuario_setor')
    op.drop_table('bem')
    op.drop_table('usuario_telefone')
    op.drop_table('usuario_papel')
    op.drop_table('setor')
    op.drop_table('log_acesso')
    op.drop_table('log_acao')
    op.drop_table('empresa_usuario')
    op.drop_table('empresa_telefone')
    op.drop_table('usuario')
    op.drop_table('empresa')
    op.drop_table('endereco')
    op.drop_table('papel_rotina')
    op.drop_table('municipio')
    op.drop_table('telefone')
    op.drop_table('rotina')
    op.drop_table('papel')
    op.drop_table('logradouro')
    op.drop_table('estado')
    # ### end Alembic commands ###


def upgrade_metadados():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcao', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcao')
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_funcao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_funcao'], ['funcao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('controle_versao_api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_responsavel', sa.Integer(), nullable=True),
    sa.Column('versao', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.Text(length=500), nullable=False),
    sa.Column('data_atualizacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_responsavel'], ['responsavel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('versao')
    )
    # ### end Alembic commands ###


def downgrade_metadados():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controle_versao_api')
    op.drop_table('responsavel')
    op.drop_table('funcao')
    # ### end Alembic commands ###

