"""empty message

Revision ID: ccfe6763370f
Revises: be2e9438e63e
Create Date: 2024-01-19 18:40:32.491940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfe6763370f'
down_revision = 'be2e9438e63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acesso', schema=None) as batch_op:
        batch_op.alter_column('data_acesso',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('log_acesso_id_empresa_fkey', type_='foreignkey')
        batch_op.drop_column('id_empresa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('log_acesso_id_empresa_fkey', 'empresa', ['id_empresa'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('data_acesso',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
