"""Incusao da coluna Bem.nome

Revision ID: cf9f37a04046
Revises: e48bf187ae91
Create Date: 2024-01-14 13:22:44.288060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9f37a04046'
down_revision = 'e48bf187ae91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bem', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
