"""Correção na tabela pelel_rotina

Revision ID: f6a3f2372970
Revises: 6a1ddc499d6f
Create Date: 2024-01-18 20:38:02.084124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a3f2372970'
down_revision = '6a1ddc499d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papel_rotina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_rotina', sa.Integer(), nullable=False))
        batch_op.drop_constraint('papel_rotina_rotina_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'rotina', ['id_rotina'], ['id'])
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('rotina_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papel_rotina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotina_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('papel_rotina_rotina_id_fkey', 'rotina', ['rotina_id'], ['id'])
        batch_op.drop_column('id_rotina')

    # ### end Alembic commands ###
