"""Inclusão de FK entre as tabelas log_acesso e empresa. correão de bug

Revision ID: 1fdeebf0b9c8
Revises: 3663ac17e20b
Create Date: 2024-01-19 17:47:15.519482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdeebf0b9c8'
down_revision = '3663ac17e20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acesso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_empresa')

    # ### end Alembic commands ###
