"""Inclusão de FK entre as tabelas log_acao e empresa

Revision ID: 3663ac17e20b
Revises: 4569a443429d
Create Date: 2024-01-19 17:44:02.074262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3663ac17e20b'
down_revision = '4569a443429d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_empresa')

    # ### end Alembic commands ###
